release.database.user=
release.database.password=
release.database.host=
release.database.port=3306

slice_current.name=slice_current
slice_previous.name=slice_previous

curator.hostURL=
curator.username=
curator.password=

personId=